<#assign PascalCaseName=NameUtil.toPascalCase(table.getRawName())>
<#assign SnakeCaseName=NameUtil.toSnakeCase(table.getRawName())>
<#assign DbStructData=table.getParent()>

#region config
fileName=${PascalCaseName}.kt
dir=pojo
#endregion

package ${namespace}.pojo

import com.kotoframework.interfaces.KPojo
import com.kotoframework.core.annotations.Table


/**
 * ${table.getRawComment()}
 * @author
 * @date ${.now?string('yyyy-MM-dd HH:mm:ss')}
 * @description  KPojo for user, generated by Kotoframework code generator
 */

@Table(name = "${table.getRawName()}")
data class User(
<#list columns as column>
    val ${NameUtil.toCamelCase(column.getRawName())}: ${column.getMapperType()}? = null, // ${column.getRawComment()}
</#list>
): KPojo