<#assign PascalCaseName=NameUtil.toPascalCase(table.getRawName())>
<#assign SnakeCaseName=NameUtil.toSnakeCase(table.getRawName())>
<#assign DbStructData=table.getParent()>

#region config
fileName=${PascalCaseName}.java
dir=domain
#endregion

package ${namespace}.domain;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.jetbrains.annotations.Nullable;

import java.time.LocalDateTime;
import java.util.List;

/**
* ${table.getRawComment()}
* @author TemplateGeneratorPlugins
* @date ${.now?string('yyyy-MM-dd HH:mm:ss')}
*/
@EqualsAndHashCode(callSuper = true)
@Accessors(chain = true)
@Data
@TableName(value = "${table.getRawName()}", autoResultMap = true)
public class ${PascalCaseName} extends BaseEntity{
<#list columns as column>
    /**
    * ${column.getRawComment()}
    */
    <#if column.hasPrimaryKey() >
        @TableId(value = "${column.getRawName()}" ${column.hasAutoGenerated()?then(", type = IdType.AUTO","")})
    <#else >
        @TableField(value = "${column.getRawName()}" ${column.getRawType()?starts_with("json")?then(", typeHandler = JacksonTypeHandler.class","")} )
    </#if>
    <#if column.getRawName()?starts_with("delet")>
        @TableLogic(value = "0", delval = "1")
    </#if>
    private ${column.getMapperType()} ${NameUtil.toCamelCase(column.getRawName())};

</#list>
}
